//! The C ABI to the Swift transcription adapters, and the two providers built
//! on top of it.
//!
//! This is a deliberately separate boundary from `audio/ffi.rs`. That one
//! carries fixed POD frames on a real-time thread and must stay allocation-free;
//! this one carries variable-length structured results on a worker thread and
//! can afford to be comfortable. Structured data crosses as UTF-8 JSON, which
//! keeps the ABI stable while provider outputs evolve and avoids
//! hand-marshalling nested arrays across two languages.
//!
//! SECURITY-REVIEW: this module owns the FFI boundary to the native
//! transcription adapters. Every pointer received from Swift is a
//! NUL-terminated UTF-8 string allocated by `strdup` on the Swift side and
//! freed here through `blueear_transcription_string_free`; nothing else
//! crosses. The JSON it contains is generated by Blue Ear's own adapter but is
//! still parsed as untrusted external data -- no path from it is ever used to
//! open a file, and a malformed payload fails the track rather than panicking.

use std::collections::HashMap;
use std::ffi::{c_char, c_void, CStr, CString};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::thread;
use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};
use crate::transcription::provider::{
    CancelToken, ProgressSink, ProviderContext, TranscriptionProvider,
};
use crate::transcription::types::{
    NotReadyReason, ProviderCapabilities, ProviderId, RawTrackResult, TrackRequest,
};

type ProgressCallbackC = extern "C" fn(*mut c_void, u64, f64);

#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
extern "C" {
    fn blueear_transcription_init(progress_callback: ProgressCallbackC, user_data: *mut c_void);
    fn blueear_transcription_probe(
        provider: *const c_char,
        models_root: *const c_char,
    ) -> *mut c_char;
    fn blueear_transcription_run(request_json: *const c_char, job_handle: u64) -> *mut c_char;
    fn blueear_transcription_cancel(job_handle: u64);
    fn blueear_transcription_string_free(ptr: *mut c_char);
}

// MARK: - Wire format

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct NativeRequest<'a> {
    provider: &'a str,
    track: &'a str,
    audio_path: String,
    models_root: String,
    diarize: bool,
    language: Option<&'a str>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NativeProbe {
    ready: bool,
    reason: Option<String>,
}

/// Fields are spelled out rather than flattened into [`RawTrackResult`]: a
/// flattened `Option` cannot cleanly express "successful response" versus
/// "error response with no payload", and this boundary is the one place where
/// getting that distinction wrong would silently produce an empty transcript.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NativeResponse {
    ok: bool,
    #[serde(default)]
    error_code: Option<String>,
    #[serde(default)]
    words: Option<Vec<crate::transcription::types::Word>>,
    #[serde(default)]
    speaker_spans: Option<Vec<crate::transcription::types::SpeakerSpan>>,
    #[serde(default)]
    model_id: Option<String>,
    #[serde(default)]
    language: Option<String>,
}

impl NativeResponse {
    fn into_result(self) -> Option<RawTrackResult> {
        Some(RawTrackResult {
            words: self.words?,
            speaker_spans: self.speaker_spans.unwrap_or_default(),
            model_id: self.model_id,
            language: self.language,
        })
    }
}

/// Maps the adapter's stable string codes onto Blue Ear's error surface.
/// Anything unrecognized becomes a generic failure rather than being passed
/// through, so a future adapter cannot invent user-visible error text.
fn map_native_error(code: Option<&str>) -> AppError {
    match code {
        Some("cancelled") => AppError::transcription_cancelled(),
        Some("models_missing") => AppError::transcription_model_missing(),
        Some("provider_not_ready") | Some("unsupported_os") | Some("not_built") => {
            AppError::transcription_provider_not_ready()
        }
        _ => AppError::transcription_failed(),
    }
}

fn map_not_ready_reason(reason: Option<&str>) -> NotReadyReason {
    match reason {
        Some("osTooOld") => NotReadyReason::OsTooOld,
        Some("notBuilt") => NotReadyReason::NotBuilt,
        Some("modelsMissing") => NotReadyReason::ModelsMissing,
        Some("languageAssetsMissing") => NotReadyReason::LanguageAssetsMissing,
        Some("notConfigured") => NotReadyReason::NotConfigured,
        _ => NotReadyReason::ProbeFailed,
    }
}

// MARK: - Progress routing

/// Native progress arrives as a job handle plus a fraction, on whatever thread
/// the adapter happens to be on. This table routes each handle back to the
/// Rust closure that owns it, so the C callback itself stays a pure lookup.
static PROGRESS_SINKS: OnceLock<Mutex<HashMap<u64, Arc<dyn Fn(f32) + Send + Sync>>>> =
    OnceLock::new();

fn progress_sinks() -> &'static Mutex<HashMap<u64, Arc<dyn Fn(f32) + Send + Sync>>> {
    PROGRESS_SINKS.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Invokes the sink *while holding the table lock*, so `ProgressRelay::drop`
/// cannot unregister a sink that is mid-call. The lock is only ever taken here
/// and in install/drop, and the sinks themselves never re-enter this module, so
/// the extra serialization costs nothing and closes the race that would
/// otherwise let a late native callback outlive its borrow.
extern "C" fn trampoline_progress(_user_data: *mut c_void, job_handle: u64, fraction: f64) {
    let Ok(guard) = progress_sinks().lock() else {
        return;
    };
    if let Some(sink) = guard.get(&job_handle) {
        sink(fraction.clamp(0.0, 1.0) as f32);
    }
}

static NEXT_JOB_HANDLE: AtomicU64 = AtomicU64::new(1);
static INITIALIZED: OnceLock<()> = OnceLock::new();

fn ensure_initialized() {
    INITIALIZED.get_or_init(|| {
        // SAFETY: registers a `'static` function pointer once for the process
        // lifetime. The `user_data` pointer is unused: progress is routed
        // through the global table above rather than through a raw pointer,
        // so there is nothing to keep alive or reclaim.
        unsafe { blueear_transcription_init(trampoline_progress, std::ptr::null_mut()) };
    });
}

/// Takes ownership of a string the Swift side allocated, copying it into Rust
/// and handing the original back to be freed.
///
/// # Safety
/// `ptr` must be either null or a NUL-terminated UTF-8 buffer allocated by the
/// native adapter and not yet freed.
unsafe fn take_native_string(ptr: *mut c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    let owned = CStr::from_ptr(ptr).to_string_lossy().into_owned();
    blueear_transcription_string_free(ptr);
    Some(owned)
}

fn probe_native(provider: ProviderId, models_root: &std::path::Path) -> Option<NotReadyReason> {
    ensure_initialized();

    let Ok(provider_c) = CString::new(provider.as_str()) else {
        return Some(NotReadyReason::ProbeFailed);
    };
    let Ok(root_c) = CString::new(models_root.to_string_lossy().as_bytes()) else {
        return Some(NotReadyReason::ProbeFailed);
    };

    // SAFETY: both pointers are valid, NUL-terminated, and only read for the
    // duration of the call; the returned string is reclaimed immediately.
    let raw = unsafe { blueear_transcription_probe(provider_c.as_ptr(), root_c.as_ptr()) };
    let Some(json) = (unsafe { take_native_string(raw) }) else {
        return Some(NotReadyReason::ProbeFailed);
    };

    match serde_json::from_str::<NativeProbe>(&json) {
        Ok(probe) if probe.ready => None,
        Ok(probe) => Some(map_not_ready_reason(probe.reason.as_deref())),
        Err(_) => Some(NotReadyReason::ProbeFailed),
    }
}

/// Runs one track through a native adapter, bridging Rust's cooperative
/// cancellation to the adapter's handle-based cancellation.
fn run_native(
    provider: ProviderId,
    request: &TrackRequest,
    models_root: &std::path::Path,
    cancel: &CancelToken,
    progress: &ProgressSink<'_>,
) -> AppResult<RawTrackResult> {
    ensure_initialized();

    if !request.audio_path.is_file() {
        return Err(AppError::track_not_found());
    }
    cancel.check()?;

    let handle = NEXT_JOB_HANDLE.fetch_add(1, Ordering::Relaxed);
    let relay = ProgressRelay::install(handle, progress);

    let request_json = serde_json::to_string(&NativeRequest {
        provider: provider.as_str(),
        track: request.track.as_str(),
        audio_path: request.audio_path.to_string_lossy().into_owned(),
        models_root: models_root.to_string_lossy().into_owned(),
        diarize: request.diarize,
        language: request.language.as_deref(),
    })
    .map_err(|_| AppError::internal("serialize native transcription request"))?;

    let request_c =
        CString::new(request_json).map_err(|_| AppError::internal("native request contained nul"))?;

    let watcher = CancellationWatcher::spawn(handle, cancel.clone());

    // SAFETY: `request_c` outlives the call; the adapter copies what it needs
    // before returning. The returned string is reclaimed immediately below.
    let raw = unsafe { blueear_transcription_run(request_c.as_ptr(), handle) };
    let response = unsafe { take_native_string(raw) };

    watcher.stop();
    drop(relay);

    let Some(json) = response else {
        return Err(AppError::transcription_failed());
    };

    let parsed: NativeResponse =
        serde_json::from_str(&json).map_err(|_| AppError::transcription_failed())?;

    if !parsed.ok {
        return Err(map_native_error(parsed.error_code.as_deref()));
    }
    // A successful response with no payload is a bug in the adapter, not a
    // reason to fabricate an empty transcript.
    parsed
        .into_result()
        .ok_or_else(AppError::transcription_failed)
}

/// Keeps a progress closure registered for the lifetime of one native call and
/// removes it on drop, including on the error paths.
struct ProgressRelay {
    handle: u64,
}

impl ProgressRelay {
    fn install(handle: u64, progress: &ProgressSink<'_>) -> Self {
        // SAFETY: the transmute extends the sink's lifetime to `'static` so it
        // can live in the global table. `ProgressRelay::drop` removes the
        // entry before `run_native` returns, and `run_native` is the only
        // frame that can end the borrow, so no call can outlive the borrow it
        // was registered under.
        let sink: &'static ProgressSink<'static> =
            unsafe { std::mem::transmute::<&ProgressSink<'_>, &'static ProgressSink<'static>>(progress) };
        let boxed: Arc<dyn Fn(f32) + Send + Sync> = Arc::new(move |fraction| sink(fraction));
        if let Ok(mut guard) = progress_sinks().lock() {
            guard.insert(handle, boxed);
        }
        Self { handle }
    }
}

impl Drop for ProgressRelay {
    fn drop(&mut self) {
        if let Ok(mut guard) = progress_sinks().lock() {
            guard.remove(&self.handle);
        }
    }
}

/// Polls Blue Ear's cancellation token and forwards a cancellation to the
/// adapter. A poll loop rather than a callback because `blueear_transcription_run`
/// blocks the calling thread for the whole inference, so there is nowhere else
/// to observe the token from.
struct CancellationWatcher {
    stop: Arc<AtomicBool>,
    handle: Option<thread::JoinHandle<()>>,
}

impl CancellationWatcher {
    fn spawn(job_handle: u64, cancel: CancelToken) -> Self {
        let stop = Arc::new(AtomicBool::new(false));
        let worker_stop = Arc::clone(&stop);
        let handle = thread::spawn(move || {
            while !worker_stop.load(Ordering::Relaxed) {
                if cancel.is_cancelled() {
                    // SAFETY: takes only a scalar handle; the adapter looks it
                    // up in its own table and ignores unknown handles.
                    unsafe { blueear_transcription_cancel(job_handle) };
                    return;
                }
                thread::sleep(Duration::from_millis(100));
            }
        });
        Self {
            stop,
            handle: Some(handle),
        }
    }

    fn stop(mut self) {
        self.stop.store(true, Ordering::Relaxed);
        if let Some(handle) = self.handle.take() {
            let _ = handle.join();
        }
    }
}

impl Drop for CancellationWatcher {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::Relaxed);
        if let Some(handle) = self.handle.take() {
            let _ = handle.join();
        }
    }
}

// MARK: - Providers

/// Apple's on-device `SpeechAnalyzer`, available from macOS 26.
///
/// No model import, no diarization: Apple's API reports what was said, not who
/// said it, so Meeting-track segments stay labelled `Meeting audio`. That is a
/// real trade-off against FluidAudio, which is why the settings screen shows
/// both providers' capabilities side by side rather than picking for the user.
pub struct AppleSpeechProvider;

impl TranscriptionProvider for AppleSpeechProvider {
    fn id(&self) -> ProviderId {
        ProviderId::AppleSpeech
    }

    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities {
            id: ProviderId::AppleSpeech,
            display_name: "Apple Speech".to_string(),
            minimum_macos: "26".to_string(),
            minimum_windows: String::new(),
            requires_model_import: false,
            supports_remote_speaker_labels: false,
            supports_word_timings: true,
            summary: "Uses the speech models built into macOS. Nothing to download, but it cannot tell meeting participants apart.".to_string(),
        }
    }

    fn probe(&self, ctx: &ProviderContext) -> Option<NotReadyReason> {
        probe_native(ProviderId::AppleSpeech, &ctx.models_root)
    }

    fn transcribe_track(
        &self,
        request: &TrackRequest,
        ctx: &ProviderContext,
        cancel: &CancelToken,
        progress: &ProgressSink<'_>,
    ) -> AppResult<RawTrackResult> {
        run_native(
            ProviderId::AppleSpeech,
            request,
            &ctx.models_root,
            cancel,
            progress,
        )
    }
}

/// FluidAudio's Parakeet ASR plus offline diarization.
///
/// The code ships in the binary but stays completely inert until selected:
/// `probe` only asks whether the required model files exist on disk, so
/// nothing in FluidAudio is initialized, and no CoreML model is loaded, for a
/// user who never chooses this provider.
pub struct FluidAudioProvider;

impl FluidAudioProvider {
    /// Repository directories a validated bundle must contain. Mirrored in
    /// `model_import::ALLOWLIST` and in `FluidAudioAdapter`; the probe checks
    /// the filesystem rather than asking FluidAudio, precisely so that probing
    /// loads nothing.
    pub const REQUIRED_REPOS: [&'static str; 2] =
        ["parakeet-tdt-0.6b-v3", "speaker-diarization-coreml"];

    /// FluidAudio is pointed at its own bundle directory rather than the
    /// shared models root, so its loaders see exactly the repo-named
    /// directories they expect and nothing else.
    fn effective_root(ctx: &ProviderContext) -> PathBuf {
        ctx.models_root
            .join(crate::transcription::model_import::FLUIDAUDIO_BUNDLE_ID)
    }
}

impl TranscriptionProvider for FluidAudioProvider {
    fn id(&self) -> ProviderId {
        ProviderId::FluidAudio
    }

    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities {
            id: ProviderId::FluidAudio,
            display_name: "FluidAudio".to_string(),
            minimum_macos: "14.4".to_string(),
            minimum_windows: String::new(),
            requires_model_import: true,
            supports_remote_speaker_labels: true,
            supports_word_timings: true,
            summary: "Runs imported speech models on this Mac. Requires a one-time model import, and can label meeting participants as separate speakers.".to_string(),
        }
    }

    fn probe(&self, ctx: &ProviderContext) -> Option<NotReadyReason> {
        let root = Self::effective_root(ctx);
        if Self::REQUIRED_REPOS
            .iter()
            .any(|repo| !root.join(repo).is_dir())
        {
            return Some(NotReadyReason::ModelsMissing);
        }
        probe_native(ProviderId::FluidAudio, &root)
    }

    fn transcribe_track(
        &self,
        request: &TrackRequest,
        ctx: &ProviderContext,
        cancel: &CancelToken,
        progress: &ProgressSink<'_>,
    ) -> AppResult<RawTrackResult> {
        run_native(
            ProviderId::FluidAudio,
            request,
            &Self::effective_root(ctx),
            cancel,
            progress,
        )
    }
}

/// Opens a native folder picker for a model bundle and returns the chosen
/// path, or `None` if the user cancelled.
///
/// SECURITY-REVIEW: the picker runs natively and hands the path straight to
/// `model_import`, so a filesystem path chosen by the user never travels
/// through the webview and the frontend cannot supply one of its own.
///
/// # Safety
/// Must be called on the main thread: it presents an `NSOpenPanel`.
pub unsafe fn pick_model_bundle_on_main_thread() -> Option<PathBuf> {
    ensure_initialized();
    let raw = blueear_transcription_pick_model_bundle();
    take_native_string(raw)
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
}

#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
extern "C" {
    fn blueear_transcription_pick_model_bundle() -> *mut c_char;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn native_error_codes_map_to_stable_app_errors() {
        use crate::error::ErrorCode;
        assert_eq!(
            map_native_error(Some("cancelled")).code,
            ErrorCode::TranscriptionCancelled
        );
        assert_eq!(
            map_native_error(Some("models_missing")).code,
            ErrorCode::TranscriptionModelMissing
        );
        assert_eq!(
            map_native_error(Some("unsupported_os")).code,
            ErrorCode::TranscriptionProviderNotReady
        );
        // An unrecognized code must not leak through as its own message.
        assert_eq!(
            map_native_error(Some("something_new")).code,
            ErrorCode::TranscriptionFailed
        );
        assert_eq!(map_native_error(None).code, ErrorCode::TranscriptionFailed);
    }

    #[test]
    fn probe_reasons_map_to_the_documented_readiness_values() {
        assert_eq!(map_not_ready_reason(Some("osTooOld")), NotReadyReason::OsTooOld);
        assert_eq!(map_not_ready_reason(Some("notBuilt")), NotReadyReason::NotBuilt);
        assert_eq!(
            map_not_ready_reason(Some("languageAssetsMissing")),
            NotReadyReason::LanguageAssetsMissing
        );
        assert_eq!(
            map_not_ready_reason(Some("who knows")),
            NotReadyReason::ProbeFailed
        );
    }

    #[test]
    fn a_successful_response_parses_into_a_raw_track_result() {
        let json = r#"{
            "ok": true,
            "words": [{"text":"hello","startSeconds":0.0,"endSeconds":0.4,"confidence":0.9}],
            "speakerSpans": [{"speakerKey":"0","startSeconds":0.0,"endSeconds":5.0}],
            "modelId": "parakeet-tdt-0.6b-v3",
            "language": "en"
        }"#;
        let parsed: NativeResponse = serde_json::from_str(json).unwrap();
        let result = parsed.into_result().unwrap();
        assert_eq!(result.words.len(), 1);
        assert_eq!(result.speaker_spans[0].speaker_key, "0");
        assert_eq!(result.language.as_deref(), Some("en"));
    }

    #[test]
    fn an_error_response_carries_no_result_payload() {
        let json = r#"{"ok": false, "errorCode": "models_missing"}"#;
        let parsed: NativeResponse = serde_json::from_str(json).unwrap();
        assert!(!parsed.ok);
        assert_eq!(parsed.error_code.as_deref(), Some("models_missing"));
        assert!(parsed.into_result().is_none());
    }

    #[test]
    fn fluidaudio_reports_models_missing_without_touching_the_native_adapter() {
        // The probe must be answerable from the filesystem alone: if it were
        // not, merely opening the settings screen would initialize FluidAudio
        // for a user who never selected it.
        let ctx = ProviderContext {
            models_root: PathBuf::from("/nonexistent/blueear-models"),
        };
        assert_eq!(
            FluidAudioProvider.probe(&ctx),
            Some(NotReadyReason::ModelsMissing)
        );
    }
}
